AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  CacheIdempotency:
    Type: AWS::ElastiCache::ServerlessCache
    Properties:
      Engine: valkey # (1)!
      ServerlessCacheName: idempotency-cache
      SecurityGroupIds: # (2)!
        - security-{your_sg_id}
      SubnetIds:
        - subnet-{your_subnet_id_1}
        - subnet-{your_subnet_id_2}

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs22.x
      Handler: index.js
      VpcConfig: # (3)!
        SecurityGroupIds:
          - security-{your_sg_id}
        SubnetIds:
          - subnet-{your_subnet_id_1}
          - subnet-{your_subnet_id_2}
      Environment:
        Variables:
          CACHE_ENDPOINT: !GetAtt CacheIdempotency.Endpoint.Address
          CACHE_PORT: !GetAtt CacheIdempotency.Endpoint.Port