/**
 * Base error type for the Batch Processing utility.
 *
 * All errors thrown by major failures extend this base class
 */
class BaseBatchProcessingError extends Error {
  public childErrors: Error[];

  public constructor(message: string, childErrors: Error[]) {
    super(message);
    this.childErrors = childErrors;
  }

  /**
   * Generates a list of errors that were generated by the major failure
   * @returns Formatted string listing all the errors that occurred
   *
   * When all batch records fail to be processed, this will generate a string like:
   *
   * @example
   * All records failed processing. 3 individual errors logged separately below.
   * ,Failed to process record.
   * ,Failed to process record.
   * ,Failed to process record.
   */
  protected formatErrors(parentErrorString: string): string {
    const errorList: string[] = [parentErrorString + '\n'];

    for (const error of this.childErrors) {
      errorList.push(error.message + '\n');
    }

    return '\n' + errorList;
  }
}

/**
 * Error thrown when all records in a batch fail to be processed.
 */
class BatchProcessingError extends BaseBatchProcessingError {
  public constructor(message: string, childErrors: Error[]) {
    super(message, childErrors);
    const parentErrorString: string = this.message;
    this.message = this.formatErrors(parentErrorString);
  }
}

export { BaseBatchProcessingError, BatchProcessingError };
