##### Labeler ##########################################################################################################
labelPRBasedOnFilePath:
  logger:
    - packages/logger/src/*
    - packages/logger/src/**/*
  tracer:
    - packages/tracer/src/*
    - packages/tracer/src/**/*
  metrics:
    - packages/metrics/src/*
    - packages/metrics/src/**/*
  idempotency:
    - packages/idempotency/src/*
    - packages/idempotency/src/**/*
  parameters:
    - packages/parameters/src/*
    - packages/parameters/src/**/*
  parser:
    - packages/parser/src/*
    - packages/parser/src/**/*
  event-handler:
    - packages/event-handler/src/*
    - packages/event-handler/src/**/*
  validator:
    - packages/validator/src/*
    - packages/validator/src/**/*
  batch:
    - packages/batch/src/*
    - packages/batch/src/**/*
  commons:
    - packages/commons/src/*
    - packages/commons/src/**/*

  layers:
    - layers/src/*
    - layers/src/**/*
    - layers/bin/*
    - layers/cdk.json

  tests:
    - packages/logger/tests/*
    - packages/logger/tests/**/*
    - packages/tracer/tests/*
    - packages/tracer/tests/**/*
    - packages/metrics/tests/*
    - packages/metrics/tests/**/*
    - packages/idempotency/tests/*
    - packages/idempotency/tests/**/*
    - packages/parameters/tests/*
    - packages/parameters/tests/**/*
    - packages/parser/tests/*
    - packages/parser/tests/**/*
    - packages/event-handler/tests/*
    - packages/event-handler/tests/**/*
    - packages/validator/tests/*
    - packages/validator/tests/**/*
    - packages/batch/tests/*
    - packages/batch/tests/**/*
    - packages/commons/tests/*
    - packages/commons/tests/**/*
    - layers/tests/*
    - layers/tests/**/*

  documentation:
    - docs/*
    - docs/**/*
    - mkdocs.yml
    - examples/app/*

  automation:
    - .github/scripts/*
    - .github/scripts/**/*
    - .github/workflows/*
    - .github/workflows/**/*
    - .github/actions/*
    - .github/actions/**/*
    - .github/release-drafter.yml
    - .github/boring-cyborg.yml
    - .github/semantic.yml

  internal:
    - .github/CODEOWNERS
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/ISSUE_TEMPLATE/*
    - CONTRIBUTING.md
    - MAINTAINERS.md
    - CODE_OF_CONDUCT.md
    - SECURITY.md
    - LICENSE
    - LICENSE-THIRD-PARTY
    - .nvmrc
    - .biome.json
    - .npmignore
    - .gitpod.yml
    - .husky/*
    - .devcontainer/*
    - packages/logger/tsconfig*.json
    - packages/logger/README.md
    - packages/metrics/tsconfig*.json
    - packages/metrics/README.md
    - packages/tracer/tsconfig*.json
    - packages/tracer/README.md
    - packages/parser/tsconfig*.json
    - packages/parser/README.md
    - packages/event-handler/tsconfig*.json
    - packages/event-handler/README.md
    - packages/idempotency/tsconfig*.json
    - packages/idempotency/README.md
    - packages/batch/tsconfig*.json
    - packages/batch/README.md
    - packages/commons/tsconfig*.json
    - packages/commons/README.md
    - packages/validator/tsconfig*.json
    - packages/validator/README.md
    - layers/tsconfig*.json
    - layers/README.md
    - examples/app/tsconfig*.json

  dependencies:
    - package.json
    - package-lock.json
    - packages/tracer/package.json
    - packages/metrics/package.json
    - packages/logger/package.json
    - packages/commons/package.json
    - packages/parameters/package.json
    - packages/idempotency/package.json
    - packages/parser/package.json
    - packages/event-handler/package.json
    - packages/validator/package.json
    - packages/batch/package.json
    - layers/package.json
    - examples/app/package.json

##### Greetings ########################################################################################################
firstPRWelcomeComment: >
  Thanks a lot for your first contribution! Please check out our [contributing guidelines](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/CONTRIBUTING.md) and don't hesitate to ask whatever you need.

  In the meantime, check out the #typescript channel on our Powertools for AWS Lambda Discord: [Invite link](https://discord.gg/B8zZKbbyET)

# Comment to be posted to congratulate user on their first merged PR
firstPRMergeComment: >
  Awesome work, congrats on your first merged pull request and thank you for helping improve everyone's experience!

# Comment to be posted to on first time issues
firstIssueWelcomeComment: >
  Thanks for opening your first issue here! We'll come back to you as soon as we can.

  In the meantime, check out the #typescript channel on our Powertools for AWS Lambda Discord: [Invite link](https://discord.gg/B8zZKbbyET)
