##### Greetings ########################################################################################################
firstPRWelcomeComment: >
  Thanks a lot for your first contribution! Please check out our [contributing guidelines](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/CONTRIBUTING.md) and don't hesitate to ask whatever you need.

  In the meantime, check out our GitHub Discussions: [Join the conversation](https://github.com/aws-powertools/powertools-lambda-typescript/discussions)
