const POWERTOOLS_DEV_ENV_VAR = 'POWERTOOLS_DEV' as const;
const POWERTOOLS_SERVICE_NAME_ENV_VAR = 'POWERTOOLS_SERVICE_NAME' as const;
const XRAY_TRACE_ID_ENV_VAR = '_X_AMZN_TRACE_ID' as const;

export {
  POWERTOOLS_DEV_ENV_VAR,
  POWERTOOLS_SERVICE_NAME_ENV_VAR,
  XRAY_TRACE_ID_ENV_VAR,
};
