Resources:
  WebsocketAPI:
      Type: AWS::AppSync::Api
      Properties:
          EventConfig:
          AuthProviders:
              - AuthType: API_KEY
          ConnectionAuthModes:
              - AuthType: API_KEY
          DefaultPublishAuthModes:
              - AuthType: API_KEY
          DefaultSubscribeAuthModes:
              - AuthType: API_KEY
          Name: RealTimeEventAPI

  WebasocketApiKey:
      Type: AWS::AppSync::ApiKey
      Properties:
          ApiId: !GetAtt WebsocketAPI.ApiId
          Description: "API KEY"
          Expires: 90

  WebsocketAPINamespace:
    Type: AWS::AppSync::ChannelNamespace
    Properties:
      ApiId: !GetAtt WebsocketAPI.ApiId
      Name: powertools