# version 9.5.2
FROM squidfunk/mkdocs-material@sha256:3678304a65e17660953a30c0a0be0bc2fb8f55ac450216c14af6ba942badc4dc

ADD requirements.txt /tmp/
RUN pip install --require-hashes -r /tmp/requirements.txt