AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  kafka

  Sample SAM Template for kafka

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    MemorySize: 512
    Tracing: Active
    Runtime: nodejs22.x
    Architectures:
      - x86_64
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: kafka-deserialization
        POWERTOOLS_METRICS_NAMESPACE: kafka-nodejs
        LOG_LEVEL: INFO
    VpcConfig:
      SubnetIds:
        - subnet-057857442d9af0852 # Replace this with your VPC's default security group ID.
        - subnet-0ec1c3a2883a36bf9
      SecurityGroupIds:
        - sg-0ec0be541d70ca3ed # Replace this with your public subnet's ID.

Resources:
  NodeJsJsonDeserializationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: json.handler
      Runtime: nodejs22.x
      Policies:
        - AdministratorAccess # For demo purposes only! Remove this for production.
      Events:
        MSKEvent:
          Type: MSK
          Properties:
            Stream: arn:aws:kafka:eu-west-3:992382490249:cluster/powertools-kafka-esm/f138df86-9253-4d2a-b682-19e132396d4f-s3
            StartingPosition: LATEST
            MaximumBatchingWindowInSeconds: 5
            Topics:
              - powertools-json-load-ts
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
          - json.ts

  NodeJsAvroDeserializationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: avro.handler
      Runtime: nodejs22.x
      Policies:
        - AdministratorAccess # For demo purposes only! Remove this for production.
      Events:
        MSKEvent:
          Type: MSK
          Properties:
            Stream: arn:aws:kafka:eu-west-3:992382490249:cluster/powertools-kafka-esm/f138df86-9253-4d2a-b682-19e132396d4f-s3
            StartingPosition: LATEST
            MaximumBatchingWindowInSeconds: 5
            Topics:
              - powertools-avro-load-ts
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
          - avro.ts

  NodeJsProtobufDeserializationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: proto.handler
      Runtime: nodejs22.x
      Policies:
        - AdministratorAccess # For demo purposes only! Remove this for production.
      Events:
        MSKEvent:
          Type: MSK
          Properties:
            Stream: arn:aws:kafka:eu-west-3:992382490249:cluster/powertools-kafka-esm/f138df86-9253-4d2a-b682-19e132396d4f-s3
            StartingPosition: LATEST
            MaximumBatchingWindowInSeconds: 5
            Topics:
              - powertools-proto-load-ts
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        EntryPoints:
          - proto.ts
