name: On new PR

on:
  workflow_run:
    workflows: ["Record PR details"]
    types:
      - completed

permissions:
  contents: read

jobs:
  get_pr_details:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable_export_pr_details.yml
    with:
      record_pr_workflow_id: ${{ github.event.workflow_run.id }}
      workflow_origin: ${{ github.event.repository.full_name }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions: 
      pull-requests: read
  check_related_issue:
    permissions:
      issues: read
      pull-requests: write
    needs: get_pr_details
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: "Debug workflow_run event"
        run: echo "${{ github }}"
      - name: "Ensure related issue is present"
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          PR_BODY: ${{ needs.get_pr_details.outputs.prBody }}
          PR_NUMBER: ${{ needs.get_pr_details.outputs.prNumber }}
          PR_ACTION: ${{ needs.get_pr_details.outputs.prAction }}
          PR_AUTHOR: ${{ needs.get_pr_details.outputs.prAuthor }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('.github/scripts/label_missing_related_issue.js')
            await script({github, context, core})
