name: Code quality

# USAGE
#
# Automatically triggered when a PR is added to the merge queue. Runs the same linting
# and unit test jobs as the PR workflow, see ./.github/workflows/reusable-run-linting-check-and-unit-tests.yml.

on:
  merge_group:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-unit-tests:
    uses: ./.github/workflows/reusable-run-linting-check-and-unit-tests.yml
